version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'

  db:
    image: postgres:10.1-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  db-admin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - 5050:80
    ## you can change pgAdmin default username/password with below environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  nginx:
    image: nginx:latest
    volumes:
      - ./build/nginx.conf:/etc/nginx/nginx.conf
      - ./app/static:/home/app/web/static
    ports:
      - 8000:80
    depends_on:
      - web

  web:
    build: ./build
    volumes:
      - ./app:/app
    expose:
      - 8000
    command: pipenv run gunicorn app.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  celery:
    build: ./build
    command: pipenv run celery -A app worker -l info
    volumes:
      - ./app:/app
    links:
      - db
      - redis

  celery-beat:
    build: ./build
    command: celery -A app beat -l info
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis

  flower:  
    image: mher/flower
    command: ["flower", "--broker=redis://redis:6379/0", "--port=8888"]  
    ports:  
      - 8888:8888  
    links:
      - db
      - redis

volumes:
  postgres_data:
  pgadmin_data:
